name: Deploy ETA Service to AWS

on:
  push:
    branches: [main]
    paths:
      - 'delivery-eta-prediction-service/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./delivery-eta-prediction-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t delivery-eta-api -f k8s/Dockerfile .

      - name: Tag and Push to ECR
        env:
          ECR_REGISTRY: 420660210456.dkr.ecr.us-east-1.amazonaws.com # Replace if different
          IMAGE_NAME: delivery-eta-api
        run: |
          docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest

      - name: Deploy to App Runner or EKS
        run: |
          echo "Please configure the exact App Runner Service ARN or EKS kubectl apply commands here."
          # aws apprunner start-deployment --service-arn arn:aws:apprunner:us-east-1:...
